theme: jekyll-theme-slate
<html>
<head>
<title>galery</title>
<meta name="discriptin" 

condect="zahrabashiry">
<meta name="keyword" 

condect="tarah,web">
</head>
<body 

bgcolor="#f9ecfa">
<center><img src="C:

\Users\Administrator

\Pictures/avatar-

01.jpg" 
></center><br><br><br><

br>
</center><br><br><br><b

r>




</body>
